### ISSUE TITLE
It would be awesome if someone made a docker container

### ISSUE THREAD

**Issue by firstkingofrome** [OpenGeoVis/PVGeo#64] opened 2020-07-15 18:23 UTC
Setting up PVGeo is very time consuming and (especially on a headless machine) difficult. This is probably a result of the complexity of getting all of the underlying python and paraview plugins to work correctly. Small changes between different machines can easily break a PVGeo installation (for example I am unable to get a working installation using the current instruction https://pvgeo.org/overview/getting-started.html#install-pvgeo breaks because the imagine library that PVGeo depends on is not available in python 2.7.15). 
**Describe the solution you'd like**
Having a docker image would greatly facilitate using PVGeo as it would eliminate these set up issues. I dont even think that it would be that difficult to make (for example https://hub.docker.com/r/kramergroup/jupyter-pyvista all ready has a nice pyVista container). If someone were interested in doing this I would greatly appreciate it. Alternatively if someone is willing to advise me when I inevitably run into problems, I am happy to try and create a container myself (which I would share on dockerhub).

Thanks

**Comment by banesullivan** [comment] 2020-07-15 18:54
I actually do have some images with ParaView working. I will see if I can track those Dockerfiles somewhere and publish an image for wide use.

Also, with the new [`ipyvtk-simple`](https://github.com/Kitware/ipyvtk-simple), https://github.com/pyvista/pyvista/pull/824, and [`ipyparaview`](https://github.com/Kitware/ipyparaview), this should be fairly straightforward (for me) to set up and deploy. I will see if I can get the time to do it this week-ish as I already have all the Dockerfiles, it's just a matter of polishing and publishing them with a few demos. 

Then we will have images ready for use with both ParaView and PyVista.

Sort of a duplicate of #60

**Comment by firstkingofrome** [comment] 2020-07-15 20:49
Oh ok thank you! I really appreciate it. Also thanks for linking the ipyparaview, that will be very helpful to me for some of my other workflows.

**Comment by banesullivan** [comment] 2020-07-17 00:43
So. I have it working and just need to push the docker images once I fix some namespacing issues when the plugins are loaded to ParaView.

Unfortunately, this issue is stemming from a bug within ParaView's Python Plugin utils that is pretty much preventing the majority of PVGeo filters/readers/sources from being used in the `pvpython` environment. This means everything is working but users cannot access any of the PVGeo plugins from ParaView as the namespace is all messed up and the plugins are har to find.

See https://discourse.paraview.org/t/python-plugin-smproxy-keyword-arguments-arent-working-as-expected/4869

In the meantime, I've pushed some minor changes to PVGeo and the needed Dockerfile to the `docker` branch here.

I'm tempted to just rename all the `labels` to the same `name` for simplicity's sake but this will totally break anyone's state files saved in ParaView with a previous version of PVGeo. Honestly, I may unapologetically do that and bump the version because for the last ~6 months I've only really been supporting PVGeo for use with PyVista.

**Comment by banesullivan** [comment] 2020-07-17 01:39
Yep, so I went ahead with the renaming to make things simple

**Comment by banesullivan** [comment] 2024-01-01 21:47
I have dropped support for ParaView, please use PyVista instead: docs.pyvista.org

PyVista provides several docker images for use: https://github.com/pyvista/pyvista/pkgs/container/pyvista

**Closed by banesullivan** 2024-01-01 21:47 UTC
